### ISSUE TITLE
Cannot install via pip on Ubuntu 12.04 Precise

### ISSUE THREAD

**Issue by cimi** [danielfrg/word2vec#25] opened 2015-10-29 16:28 UTC
When running:

```
➜  word2vec git:(master) pip install word2vec
```

I get back:
```
Collecting word2vec
  Using cached word2vec-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/cc89ypZ6.s: Assembler messages:
    /tmp/cc89ypZ6.s:2867: Error: no such instruction: `vfmadd312ss (%r12),%xmm0,%xmm11'
    /tmp/cc89ypZ6.s:2886: Error: no such instruction: `vfmadd312ss 4(%r12),%xmm0,%xmm1'
    [many, many more]
    /tmp/cc89ypZ6.s:5426: Error: no such instruction: `vfmadd312ss (%rdx,%r9,4),%xmm0,%xmm2'
    /tmp/cc89ypZ6.s:5429: Error: no such instruction: `vfmadd312ss (%rdx,%rdi,4),%xmm0,%xmm15'
    gcc word2vec-c/word2vec.c -o bin/word2vec -lm -pthread -O3 -Wall -march=native -funroll-loops -Wno-unused-result

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xYMfux/word2vec
```

And the installation fails.

```
➜  word2vec git:(master) uname -a
Linux uf8bc12856564545249ca 3.13.0-66-generic #108~precise1-Ubuntu SMP Thu Oct 8 10:07:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if you need more information about my environment. If the entire `Error: no such instruction` stuff is useful to you I can provide it.

Thanks for building this. I've used it on OSX and I like it!

**Comment by danielfrg** [comment] 2015-10-29 20:17
Thanks for the report, Is that the entire output? if not can you paste it?
More information about the env would be nice. Are you using anaconda?

**Comment by ianbstewart** [comment] 2015-11-18 23:14
I'm also facing this exact problem on OSX. Would be great to know if there's been an update.

**Comment by cimi** [comment] 2015-11-19 01:41
Sorry for not replying earlier, but this somehow slipped my mind.

```
➜  ~  pyenv versions
  system
  2.7.9
* anaconda-2.1.0 (set by /home/local/ANT/ciminian/.python-version)
```

Full output:
* [Anaconda](http://pastebin.com/TdGCtymZ)
* [python 2.7.9](http://pastebin.com/3GFUVYjy)

Installing worked for me about a month ago on OSX, I can run word2vec now. On Mac I am using pyenv and python 2.7.9.

**Comment by monkey2000** [comment] 2015-11-21 02:46
@cimi 
> gcc word2vec-c/word2vec.c -o bin/word2vec -lm -pthread -O3 -Wall -march=native -funroll-loops -Wno-unused-result

Try using `-march=corei7` instead of `native`

**Comment by cimi** [comment] 2015-11-23 14:18
I don't seem to be able to override `CFLAGS` for word2vec, running:

```
➜  ~  CFLAGS='-march=corei7' pip install word2vec
```
Still gives me the `-march=native` output (identical to the previous).

However, on my system, the native architecture seems to be seems `corei7-avx`, so I'm not sure that this will fix it?

```
➜  ~  gcc -march=native -E -v - </dev/null 2>&1 | grep cc1
 /usr/lib/gcc/x86_64-linux-gnu/4.6/cc1 -E -quiet -v -imultilib . -imultiarch x86_64-linux-gnu - -march=corei7-avx -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mno-tbm -mavx -msse4.2 -msse4.1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=generic -fstack-protector
```

I've neved fiddled with C compilation through pip, and I haven't fiddled with C in a while so please let me know if I'm not doing something I should be doing.

**Comment by cimi** [comment] 2015-11-23 14:53
@monkey2000 - Thank you! That fixed it.

I cloned the repo, changed `-march=native` in setup.py to `-march=corei7` and it built successfully.

I still don't know how to override when installing via pip from remote. I was expecting setting CFLAGS to work but it does not.

**Comment by monkey2000** [comment] 2015-11-24 12:26
@cimi This problem comes from the unsupported instructions on particular CPUs. I think the fix code is platform-related.

Hopefully you can create a pull/request and submit your code to this project.

**Comment by danielfrg** [comment] 2015-11-24 18:56
Hi guys, sorry i haven't been paying a lot of attention to this.

I just added an option to use an env variable to overwrite the compilation flags: https://github.com/danielfrg/word2vec/commit/57011df3e81a74337714b3909a26e5ff68ec9a2c. So now you should be able to do: `CFLAGS='-march=corei7' pip install word2vec`.

I would also merge any PR that fixes this issue for that architecture but in my tests inside of this docker container (https://github.com/danielfrg/word2vec/blob/master/Dockerfile) It works for me so i cannot reproduce at the moment.

**Comment by danielfrg** [comment] 2015-11-24 19:00
I just realised the container I use is based on `debian` not `ubuntu` so that might explain why i dont get this error.

**Comment by danielfrg** [comment] 2015-12-11 02:29
I am closing this since now its possible to override the flags while doing `pip install`. Reopoen or open a new issue if this is still an issue.

**Closed by danielfrg** 2015-12-11 02:29 UTC
